// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Linq;
using MonoTouch.Dialog;
using Foundation;
using UIKit;

namespace HandoffDemo
{
	public partial class CarsViewCtrl : DialogViewController
	{
		public CarsViewCtrl (IntPtr handle) : base (handle)
		{
			
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			var vehicles = Vehicle.GetVehicles ();

			/// Create StringElement to store vehicle detail for each vehicle.
			StringElement[] VehicleElements = new StringElement[vehicles.Length];
			for (int i = 0; i < VehicleElements.Length; i++) {
				VehicleElements [i] = new StringElement (vehicles [i].ToString ());
			}

			/// Set Dialog View Controller root to show all vehicles
			this.Root = new RootElement ("Vehicles") { 
				new Section() {
					VehicleElements
				}
			};

			/// What to do when handoff has occurred. 
			var appDelegate = (AppDelegate) UIApplication.SharedApplication.Delegate;
			appDelegate.HandoffOccurred += (object sender, HandoffArgs e) => {
				var vehicle = vehicles.First(x=>x.VIN == e.VIN);
				new UIAlertView("Handoff Occurred", "Vehicle Handed Off\n" + vehicle.ToString(), null, "OK").Show();
			};
		}
	}
}
