// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace HandoffDemo
{
	public partial class CarsViewCtrl : UIViewController
	{
		public CarsViewCtrl (IntPtr handle) : base (handle)
		{
		}
	}
}
